'use strict';
const { _electron: electron } = require('playwright-core');
const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const testRoot = path.join(root, 'test-results', `curation-${Date.now()}`);
const hash = b => crypto.createHash('sha256').update(b).digest('hex');
const passed = []; let instance, server, page;
const pass = name => { passed.push(name); console.log('PASS:', name); };
(async () => {
  await fs.mkdir(testRoot, { recursive: true });
  const png = await fs.readFile(path.join(__dirname, 'fixtures', 'first.png'));
  server = http.createServer((req, res) => {
    if (req.url.endsWith('.png')) { res.setHeader('Content-Type', 'image/png'); res.end(png); return; }
    if (req.url.endsWith('.svg')) { res.setHeader('Content-Type', 'image/svg+xml'); res.end('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="120"><rect width="600" height="120" fill="#789"/></svg>'); return; }
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    if (req.url === '/unknown') { res.end('<title>Unknown layout</title><div><img src="/u.png" alt="Unlabelled page"></div>'); return; }
    res.end(`<!doctype html><title>Curation fixture</title><style>body{margin:0}img{display:block;width:200px;height:120px}header,nav,footer{display:flex}.reading-strip{width:430px}.reading-strip img{width:420px;height:560px}.reading-strip img.short{height:120px}.bg{width:420px;height:560px;background-image:url('/bg.png')}</style>
      <header><img src="/logo.png" alt="Site logo"><img src="/shared.png" alt="Header badge"></header><nav><img src="/icon.png" alt="Menu icon"></nav>
      <main><img src="/cover.png" alt="Cover"><section class="reading-strip"><img src="/p1.png" alt="Page 1"><img src="/p2.png" alt="Page 2"><canvas width="420" height="560" aria-label="Page 3"></canvas><img class="short" src="/short.svg" alt="Short final page"><div class="bg"></div><img src="/shared.png" alt="Main duplicate"></section><aside><img src="/rec.png" alt="Recommended book"></aside></main>
      <div class="comments"><img src="/avatar.png" alt="Reader avatar"></div><footer><img src="/partner.png" alt="Partner"></footer>
      <script>const c=document.querySelector('canvas');const x=c.getContext('2d');x.fillStyle='#548';x.fillRect(0,0,420,560);</script>`);
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const executablePath = process.argv[2];
  instance = await electron.launch({ ...(executablePath ? { executablePath, args: ['--eiw-test'] } : { args: [root, '--eiw-test'] }), env });
  page = await instance.firstWindow(); await page.waitForFunction(() => !!window.eiw);
  await page.selectOption('#browserMode','electron');
  const uiErrors = []; page.on('pageerror', error => uiErrors.push(error.message));
  await instance.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].show());
  await page.fill('#url', `${base}/curation`); await page.check('#backgrounds');
  await page.click('#advancedToggle'); await page.fill('#waitMs', '350'); await page.fill('#maxSteps', '45');
  async function scan() { await page.click('#scan'); await page.waitForFunction(() => !busy && all.length > 0, null, { timeout: 45000 }); }
  await scan();
  const raw = await page.evaluate(() => all); assert.equal(raw.length, 13);
  assert.equal(await page.evaluate(() => visibleItems().length), 12);
  assert.ok(raw.find(x => x.alt === 'Site logo').filterHints.chrome);
  assert.equal(raw.find(x => x.alt === 'Page 3').filterHints.mainKind, 'reader');
  pass('scan tags IMG, Canvas and background context without removing results');
  await page.check('#hideChrome');
  const hiddenChrome = await page.evaluate(() => visibleItems());
  assert.equal(hiddenChrome.length, 7); assert.ok(hiddenChrome.some(x => x.alt === 'Main duplicate'));
  assert.ok(!hiddenChrome.some(x => x.filterHints.chrome));
  pass('logo, menu, recommendations and comments hide without dropping duplicate content');
  await page.check('#mainOnly');
  const primary = await page.evaluate(() => visibleItems());
  assert.equal(primary.length, 6); assert.ok(primary.some(x => x.alt === 'Short final page'));
  assert.ok(primary.some(x => x.source === 'background')); assert.ok(primary.some(x => x.source === 'canvas'));
  pass('main-only chooses the reader and preserves short pages and backgrounds');
  await page.selectOption('#sourceFilter', 'canvas');
  assert.equal(await page.evaluate(() => visibleItems().length), 1);
  pass('source filter can isolate Canvas');
  await page.selectOption('#sourceFilter', 'all');
  await page.click('#reverseOrder');
  const ordered = await page.evaluate(() => exportItems());
  await instance.evaluate((_, dir) => global.__eiwTest.setOutput(dir), testRoot);
  await page.fill('#setName', 'Filtered pages'); await page.click('#download');
  await page.waitForFunction(() => !busy && document.getElementById('status').textContent.startsWith('บันทึกเสร็จ'));
  const savedRoot = path.join(testRoot, 'Filtered pages');
  const report = JSON.parse(await fs.readFile(path.join(savedRoot, 'report.json'), 'utf8'));
  assert.equal(report.failed, 0); assert.equal(report.saved, 6);
  assert.deepEqual(report.files.map(x => x.source), ordered.map(x => x.url));
  const savedHashes = {};
  for (const entry of report.files) savedHashes[entry.filename] = hash(await fs.readFile(path.join(savedRoot, entry.filename)));
  pass('export uses only selected visible images with contiguous numbers and reversed order');
  const completedStatus = await page.textContent('#status');
  await instance.evaluate(({BrowserWindow}) => {
    const main = BrowserWindow.getAllWindows().find(w => w.webContents.getURL().startsWith('eiw://app'));
    main.webContents.send('eiw:event', {type:'download-progress',index:6,total:6,saved:5,failed:0});
  });
  await page.waitForTimeout(150);
  assert.equal(await page.textContent('#status'), completedStatus);
  pass('late download progress cannot overwrite a completed export status');
  const beforeOrder = await page.evaluate(() => sequence.slice());
  await page.click('#removeSelected'); await page.click('#collectionCancel');
  assert.equal(await page.evaluate(() => all.length), 13);
  pass('cancel removal leaves all results intact');
  await page.click('#removeSelected'); await page.click('#collectionAccept');
  await page.waitForFunction(() => !busy && all.length === 7);
  const backend = await instance.evaluate(() => global.__eiwTest.getState());
  assert.equal(backend.count, 7); assert.equal(backend.excluded, 6);
  assert.equal(await page.evaluate(() => visibleItems().length), 0);
  const removedExport = await page.evaluate(id => window.eiw.download({ ids: [id] }), ordered[0].id);
  assert.equal(removedExport.ok, false);
  pass('remove affects only selected visible results and rejects exporting removed IDs');
  await page.click('#resetFilters'); assert.equal(await page.evaluate(() => all.length), 7);
  pass('resetting filters does not resurrect removed images');
  await page.click('#undoRemove'); await page.waitForFunction(() => !busy && all.length === 13);
  assert.deepEqual(await page.evaluate(() => sequence.slice()), beforeOrder);
  assert.equal((await instance.evaluate(() => global.__eiwTest.getState())).excluded, 0);
  pass('undo restores selection, records and manual order');
  await page.click('#deselectAll');
  assert.equal(await page.isDisabled('#removeSelected'), true);
  await page.locator('.card input[type=checkbox]').first().check();
  await page.click('#removeSelected'); await page.click('#collectionAccept');
  await page.waitForFunction(() => !busy && all.length === 12);
  await page.click('#undoRemove'); await page.waitForFunction(() => !busy && all.length === 13);
  pass('individual checkbox selection removes one item and supports undo');
  const invalid = await page.evaluate(() => window.eiw.removeItems({ ids: ['invalid-id'] }));
  assert.equal(invalid.ok, false); assert.equal((await instance.evaluate(() => global.__eiwTest.getState())).count, 13);
  pass('invalid collection IDs fail without changing state');
  await page.check('#hideChrome'); await page.check('#mainOnly');
  await page.screenshot({ path: path.join(testRoot, 'curation-wide.png'), fullPage: true });
  await page.setViewportSize({ width: 980, height: 700 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(testRoot, 'curation-narrow.png') });
  pass('new controls fit the minimum supported window width');
  const stateBeforeClear = await instance.evaluate(() => global.__eiwTest.getState());
  assert.ok(stateBeforeClear.canvasTempDir); await fs.access(stateBeforeClear.canvasTempDir);
  await page.click('#clearResults'); await page.click('#collectionCancel');
  assert.equal(await page.evaluate(() => all.length), 13);
  await page.click('#clearResults'); await page.click('#collectionAccept');
  await page.waitForFunction(() => !busy && all.length === 0);
  assert.equal((await instance.evaluate(() => global.__eiwTest.getState())).count, 0);
  await assert.rejects(fs.access(stateBeforeClear.canvasTempDir));
  pass('clear-all confirms and clears hidden records, undo state and temporary Canvas files');
  assert.equal(await page.inputValue('#url'), `${base}/curation`);
  assert.equal((await page.evaluate(() => window.eiw.settings())).data.outputRoot, testRoot);
  for (const [filename, digest] of Object.entries(savedHashes)) assert.equal(hash(await fs.readFile(path.join(savedRoot, filename))), digest);
  pass('removal and clear never modify exported files, URL or destination folder');
  await page.fill('#url', `${base}/unknown`); await scan();
  assert.equal(await page.evaluate(() => visibleItems().length), 1);
  assert.match(await page.textContent('#filterSummary'), /ระบุเขตหลักไม่ชัด/);
  pass('unknown layouts fail open with a warning instead of hiding all images');
  await page.click('#scan');
  await page.waitForFunction(() => busy);
  assert.equal(await page.isDisabled('#removeSelected'), true);
  assert.equal(await page.isDisabled('#clearResults'), true);
  assert.equal(await page.isDisabled('#mainOnly'), true);
  const race = await page.evaluate(() => window.eiw.clearResults());
  assert.equal(race.ok, false);
  await page.waitForFunction(() => !busy);
  pass('collection changes are blocked during a scan in both UI and backend');
  await page.click('#selectAll');
  await page.click('#removeSelected'); await page.click('#collectionAccept');
  await page.waitForFunction(() => !busy && all.length === 0);
  assert.equal(await page.isDisabled('#clearResults'), false);
  await page.click('#clearResults'); await page.click('#collectionAccept');
  await page.waitForFunction(() => !busy && removedSnapshot === null);
  assert.equal((await instance.evaluate(() => global.__eiwTest.getState())).excluded, 0);
  pass('clear also releases records when every image has been removed');
  assert.deepEqual(uiErrors, []);
  pass('no renderer JavaScript errors during the complete workflow');
  await fs.writeFile(path.join(testRoot, 'results.json'), JSON.stringify({ version: '1.0.4', passed: passed.length, tests: passed, executable: executablePath ? 'packaged' : 'source' }, null, 2));
  console.log(`ALL ${passed.length} CURATION CHECKS PASSED. Artifacts: ${testRoot}`);
})().catch(async error => {
  console.error(error.stack || error); process.exitCode = 1;
  await page?.screenshot({ path: path.join(testRoot, 'failure.png') }).catch(() => {});
  await fs.writeFile(path.join(testRoot, 'failure.txt'), String(error.stack || error)).catch(() => {});
}).finally(async () => {
  if (instance) await instance.close().catch(() => {});
  if (server) { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); }
});
